### ISSUE TITLE
Publishing node-gsettings npm package

### ISSUE THREAD

**Issue by vilnius-leopold** [GPII/linux#69]
In search for a node.js binding for `dconf` I stumbled upon your `gsettings` binding. I built it locally and it serves me well. So thanks for making this code available under the BSD license!

Currently though it is part of the `gsettingsBridge` package which itself is part of the `linux` package. It would make it easier for me and other people to discover, install and contribute to the gsettings binding if it would be a stand-alone package, preferably published via npm.

I would also be interested in making this happen myself. But instead of silently forking it I thought it might be better if upstream is involved - not to duplicate efforts. Would you be interested in making this happen?

**Comment by vilnius-leopold** [comment]
I got impatient, so I forked it. I implemented support for some additional types. Might be useful for you guys as well.
https://github.com/vilnius-leopold/node-gsettings

**Comment by javihernandez** [comment]
Hey @vilnius-leopold, 

it's awesome to see that our code is useful to other people! :)
Sorry for the silence, but this is something I wanted to raise in our weekly meeting before providing a "consolidated" answer, so we will let you know our decision on this ASAP.

Meanwhile, in my opinion, I'm okay with splitting it out from the linux repository and keeping it apart as a separate module. Also, this is something that can probably apply to some of our add-ons, but our linux repo would need some work to make it possible, and right now we're busy working on other things.
Personally, I don't have anything against your fork (forking is good), but we are always happy to receive new contributions from people outside of the project. So if we finally decide to spend some time on making this, it would be great to receive your changes back; the benefits? We're a community in constant development, our projects are under a clear and open governance (https://wiki.gpii.net/w/GPII_Technical_Governance), and the most important thing, our software is being updated regularly, well tested and validated from many people.

**Comment by vilnius-leopold** [comment]
@javihernandez I'm glad you're considering my proposal. 

I want to contribute back once the module is split off. The part of code we both (and potentially others) are interested in is essentially the `nodegsettings.cpp` binding without the `gsettingsBridge.js` and currently there are no independent tests for only the binding. As far as I understand, the test suite requires `universal` and `gsettingsBridge` to be run. That is a bit painful for people like me who don't want to pull/build/install the entire project only to run tests for the binding.

The https://github.com/vilnius-leopold/node-gsettings fork is basically a proposal for how I would imagine the module to work. Please feel free to through in your thoughts as I have very little experience in (partially) forking projects / collaborating on splitting up someone else's project.

I think for this module not to end up in two independent projects we would have to agree on couple of things like:
- how should the public API look like
- who will maintain the repository/package

**Comment by colinbdclark** [comment]
I, for one, think it would be great to split out our node-gsettings code into a standalone module and to start growing a community of users around it.

Assuming it won't have a huge impact on the gpii-linux repository, I'm a +1.

Thanks for bringing this up and getting it started, @vilnius-leopold.

**Comment by vilnius-leopold** [comment]
@colinbdclark I think the impact would be minimal. The separate module would basically only be a wrapper script around the current c++ binding, exposing a more convenient/extensible API. 

As I see it from looking at [gsettings_bridge.js](https://github.com/GPII/linux/blob/master/gpii/node_modules/gsettingsBridge/gsettings_bridge.js) all you would have to do is to replace the calls to the native c++ binding with those of the new module. E.g.

```javascript
// var nodeGSettings = require("./nodegsettings/build/Release/nodegsettings.node");
var GSettings = require('node-gsettings') // new module

/* 
gpii.gsettings.getSingleKey = function (schemaId, key) {
        return nodeGSettings.get_gsetting(schemaId, key);
};
*/
gpii.gsettings.getSingleKey = function (schemaId, key) {
        var settings = new GSettings(schemaId)
        return settings.get(key);
};
```
And if I'm right, the tests should not be affected by the switch as they only test `gsettings_bridge.js` and don't care about who does the gsettings API calls under the hood.

**Comment by amb26** [comment]
Thanks, @vilnius-leopold - I've created a GPII repo at https://github.com/GPII/node-gsettings - if you would like, you could make a pull request against this. To be accepted as a core GPII repo, the contents would need to go through a review process - see @javihernandez link above. I'm very happy you're prepared to put work into this package since we have not had the resources to look at it for a long time. As you say, in order to avoid diverging, we'd need to agree on the public API form and maintenance responsibility. I've issued some comments to your pull request - of which my main one is a preference for an "instance-free API" since I think this would more closely reflect an expected usage pattern as well as being slightly more efficient.
